name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - uses: pnpm/action-setup@master
        with:
          version: latest

      - name: Install Node.js dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build:prod

      - uses: ncipollo/release-action@main
        with:
          artifacts: 'dist/*'
          makeLatest: true

      - name: Publish
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH }}
